name: bubbles-keep-alive-service

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  ping-service:
    runs-on: ubuntu-latest

    steps:
      - name: curl request to ping bubbles api service
        run: curl -sSf https://bubbles-api-yn2d.onrender.com/health