name: bubbles-keep-alive-service

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  ping-service:
    runs-on: ubuntu-latest

    steps:
      - name: curl request to ping bubbles-api health service every 1min
        run: curl -sSf https://bubbles-api-a6hm.onrender.com/health
